---
- name: config neutron api paste
  file:
    src: /usr/share/neutron/api-paste.ini
    dest: /etc/neutron/api-paste.ini
    owner: neutron
    group: neutron
    state: link

- name: config neutron plugins
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    owner: neutron
    group: neutron
    state: link

- name: config neutron common
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: neutron
    group: neutron

- name: config neutron server
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: neutron
    group: neutron

- name: config neutron openvswitch agent
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner: neutron
    group: neutron

- name: config neutron dhcp agent
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    owner: neutron
    group: neutron

- name: config neutron l3 agent
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    owner: neutron
    group: neutron

- name: config neutron metadata agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    owner: neutron
    group: neutron
